server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: xqr123456
    url: jdbc:mysql://localhost:3306/goods?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: com.bosssoft.springboot5_31  #别名
  mapper-locations: classpath:/mapper/*.xml #xml文件
